import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/navigation/NavigationBar";
import Footer from "@/components/navigation/Footer";
import { AuthContextProvider } from "@/context/AuthContext";
import { CategoryContextProvider } from "@/context/CategoryContext";

const titi = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={titi.className}>
        <div className="page">
          <AuthContextProvider>
            <CategoryContextProvider>
              <NavigationBar
                logo={"" || "/img/grillo.svg"}
                name={"Ecommerce"}
                profile={"profile"}
                cart={"cart"}
              />
              {children}
              <Footer
                fb={""}
                ig={""}
                wp={""}
                info={`© 2024 VALENTIN LIBONATI. Teléfonos. Si sos Consultor y tenés alguna duda sobre tu venta presencial, podés llamar al: 0810-444-0505 (Int. del país) o 4-837-6000 (Capital y GBA).`}
              />
            </CategoryContextProvider>
          </AuthContextProvider>
        </div>
      </body>
    </html>
  );
}
