import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/navigation/NavigationBar";
import { useRouter } from "next/navigation";

const titi = Titillium_Web({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={titi.className}>
        <div className="page">
          <NavigationBar
            logo={"" || "/img/grillo.svg"}
            name={"Ecommerce"}
            profile={"profile"}
            cart={"cart"}
          />
          {children}
        </div>
      </body>
    </html>
  );
}
